const CONFLICT_ERROR_CODE = 409;
const CONFLICT_ERROR_MESSAGE = 'Пользователь с таким email уже зарегистрирован'
const UNAUTHORIZED_ERROR_CODE = 401;
const UNAUTHORIZED_ERROR_MESSAGE = 'Неправильные почта или пароль'
const SUCCESS_UPDATE_USER_MESSAGE = 'Данные успешно обновлены'
const SUCCESS_REGISTRATION_MESSAGE = 'Регистрация прошла успешно'
const SERVER_ERROR_MESSAGE = 'При выполнении запроса произошла ошибка. Попробуйте еще раз или обратитесь к администратору'

const DURATION_SHORT_MOVIES = 40;
const USER_WINDOW_WIDTH_480 = 480;
const START_NUMBERS_OF_MOVIES_MOBILE = 5;
const START_NUMBERS_OF_MOVIES = 4;
const MORE_BUTTON_NUMBERS_OF_MOVIES_MOBILE = 2;
const MORE_BUTTON_NUMBERS_OF_MOVIES = 1;



module.exports = {
    CONFLICT_ERROR_CODE,
    CONFLICT_ERROR_MESSAGE,
    UNAUTHORIZED_ERROR_CODE,
    UNAUTHORIZED_ERROR_MESSAGE,
    SUCCESS_UPDATE_USER_MESSAGE,
    SUCCESS_REGISTRATION_MESSAGE,
    SERVER_ERROR_MESSAGE,
    DURATION_SHORT_MOVIES,
    USER_WINDOW_WIDTH_480,
    START_NUMBERS_OF_MOVIES_MOBILE,
    START_NUMBERS_OF_MOVIES,
    MORE_BUTTON_NUMBERS_OF_MOVIES_MOBILE,
    MORE_BUTTON_NUMBERS_OF_MOVIES
}